### ISSUE TITLE
Problem with lazySizes.autoSizer.checkElems() and images disappearing

### ISSUE THREAD

**Issue by roopemerikukka** [aFarkas/lazysizes#136]
I'm using lazysizes and respimage libraries and I'm appending the img markup with ```sizes="auto"``` to opened modal with jQuery. The modal opens from state of css scale 0 to scale 1 and if I don't use the ```lazySizes.autoSizer.checkElems();``` function the lowest quality image is beaing loaded. If I use the function the high quality image gets loaded but it sometimes only flashes and disappears after that. This only happens with Firefox 39 and pagespeed enabled.

Disabling the pagespeed from the server solves the problem but I wouldn't like to do that. I'm not sure if the problem is within the pagespeed or lazysizes or the combination of them. The server runs nginx and the pagespeed doesn't have it's lazyload enabled.

**Comment by aFarkas** [comment]
@roopemerikukka 
Can you give me a link? I really need to see this.

**Comment by roopemerikukka** [comment]
@aFarkas 
http://imagon.com/en/contact/

If you open some of those countries and click the persons image the modal opens. The image inside the modal disappears something like every fifth time.

**Comment by aFarkas** [comment]
I couldn't replicate your FF disappearing issue. For me this sounds like a Firefox issue. That might happen with some special Caching involved. Is there something suspicious with cacheing? Does the image already have to be in cache or was never in cache, if this happens?

What does:

```js
document.querySelector('.js-single-employee-modal img').currentSrc;
//and
document.querySelector('.js-single-employee-modal img').complete
```

return?

About the fact, that you need to call `lazySizes.autoSizer.checkElems()`, could you please retry the newest version in master. I think I fixed this, so you don't need to call it. Please report back, if at least this is fixed. Maybe your other bug also disappears (but it will be still important to know, what is going wrong).

**Comment by roopemerikukka** [comment]
The first one returns images url and the second returns ```true```. There also seems to be this ```GET``` request without headers occuring when the image disappears (see screenshot).

![screenshot 2015-08-04 14 20 33](https://cloud.githubusercontent.com/assets/1453463/9059637/53eaccb0-3ab4-11e5-98a3-1892d211d7de.png)


I'll try to update to the latest master and get back to you if the problem still occurs or has solved by doing that.

**Comment by aFarkas** [comment]
Not sure, also found these:
https://bugzilla.mozilla.org/show_bug.cgi?id=941823
https://github.com/pagespeed/ngx_pagespeed/issues/370

**Comment by roopemerikukka** [comment]
Updating to the latest master didn't fix the problem. The broken image has DOM properties ```clientHeight```, ```height```, ```naturalHeight``` and  ```naturalWidth``` values 0 (unlike normally loading image of course).

**Comment by aFarkas** [comment]
@roopemerikukka 
Does it "fix" the problem that you have to re-call `lazySizes.autoSizer.checkElems()` to get the right sizes?

**Comment by roopemerikukka** [comment]
Yes that got fixed with the latest master.

**Comment by aFarkas** [comment]
@roopemerikukka 

I again tried to replicate as also asked around, but couldn't find anyone (out of 3) to replicate this issue. In fact the error message makes it seem to be Firefox/Pagespeed related, because this has something to do with decoding and lazysizes doesn't change anything with the image data or the response header.

**Comment by aFarkas** [comment]
@roopemerikukka 
Have you any new information on this? Maybe a bugreport at mozilla?

(As I said I couldn't replicate it, but maybe some mozilla engineer knows more.)

**Comment by roopemerikukka** [comment]
@aFarkas

I haven't been able to replicate the problem again so I'm thinking if it's caused by our server caching + pagespeed combination. I'll close the issue for now and make the bug report to mozilla if the problem occurs again. If I need to make the bug report I'll link it to here also.
