### ISSUE TITLE
BGSet - not working in ie11

### ISSUE THREAD

**Issue by cdwebdev** [aFarkas/lazysizes#272]
It appears that when I am using bgset along with lazy sizes, IE11 does not load the lazy image after I reload the page a couple of times. The lazy load script does get fired as I can see the class name change to loaded. Please advise.

**Comment by cdwebdev** [comment]
Update: Im running debug breakpoints within while running it in IE.
It seems to fail around here ls.bgset.js  where it does not set the image:
	var proxyLoad = function(e){
		if(!e.target._lazybgset){return;}

		var image = e.target;
		var elem = image._lazybgset;
		var bg = image.currentSrc || image.src;

		if(bg){
			elem.style.backgroundImage = 'url('+ bg +')';
		}

		if(image._lazybgsetLoading){
			lazySizes.fire(elem, '_lazyloaded', {}, false, true);
			delete image._lazybgsetLoading;
		}
	};

**Comment by aFarkas** [comment]
Thank you can you give me a test case?

**Comment by cdwebdev** [comment]
Hi,
I am noticing the issue on this link.
Simply try reloading the place a couple of times in IE and you will see the
image stop loading.
http://www.sho.com/dice

**Comment by cdwebdev** [comment]
I have submitted a test case via code pen: http://codepen.io/cdwebdemo/pen/beGNWb 
Please let me know if this helps.

**Comment by aFarkas** [comment]
Thanks. Give me 2-3 days to look into it.

**Comment by aFarkas** [comment]
I could replicate your issue only in IE10, not IE11. However, with the newest version of lazysizes/bgset in the master branch, your issue should be fixed.

Please close if this helps.

**Comment by dwolf83** [comment]
I'm also having this issue in FireFox and it still seems to be an issue even with latest pull of 2.0.0

**Comment by aFarkas** [comment]
@dwolf83 
Do you have a test case for this? The demos work just fine:
http://jsfiddle.net/trixta/w96o9xm5/
http://jsfiddle.net/trixta/bfqqnosp/embedded/result/

**Comment by schuylr** [comment]
I've run through all of this in BrowserStack.

The demo is still an issue for IE10, but not IE11. Firefox is fine.

However, IE11 doesn't work for `data-bgset` on my own website for whatever reason.

IE Edge 12 works for regular `data-srcset`, but doesn't work for `data-bgset`.

IE Edge 13 works perfectly.

**Comment by aFarkas** [comment]
@schuylr 
I just have retested the following links in IE 10:
http://jsfiddle.net/trixta/w96o9xm5/
http://jsfiddle.net/trixta/bfqqnosp/

And those work just fine, in my IE10.

Can you give me a link to your website? (You can also mail me).

**Comment by schuylr** [comment]
@aFarkas Sorry - thought I made an edit. I found that everything works great once I use picturefill - but not respimg. Respimg fixes a few edge cases but not all.

**Comment by iamdarrenhall** [comment]
@aFarkas Images aren't loading for me in IE when the following format is used ([jsfiddle example)](http://jsfiddle.net/6so25dkn/2/): 

```
 data-bgset="
          http://lorempixel.com/1920/768/nightlife/1/, 
          http://lorempixel.com/2880/1152/nightlife/1/ 2x [(min-width: 1200px)] |     
          http://lorempixel.com/1200/768/nightlife/1/, 
          http://lorempixel.com/1800/1152/nightlife/1/ 2x [(min-width: 800px)] |           
          http://lorempixel.com/800/770/nightlife/1/, 
          http://lorempixel.com/1200/1155/nightlife/1/ 2x [(min-width: 480px)] | 
          http://lorempixel.com/480/784/nightlife/1/, 
          http://lorempixel.com/720/1176/nightlife/1/ 2x
"
```

It works on Chrome, Firefox and Safari though.

**Comment by aFarkas** [comment]
This is by design. The width descriptor already includes the features of the density (x) descriptor. Therefore the respimg polyfill plugin does not polyfill this feature. 

You can simply rewrite your markup to this:

```
data-bgset="
          http://lorempixel.com/1920/768/nightlife/1/ 1920w, 
          http://lorempixel.com/2880/1152/nightlife/1/ 2880w [(min-width: 1200px)] |     
          http://lorempixel.com/1200/768/nightlife/1/ 1200w, 
          http://lorempixel.com/1800/1152/nightlife/1/ 1800w [(min-width: 800px)] |           
          http://lorempixel.com/800/770/nightlife/1/ 800w,
          http://lorempixel.com/1200/1155/nightlife/1/ 1200w [(min-width: 480px)] | 
          http://lorempixel.com/480/784/nightlife/1/ 480w,
          http://lorempixel.com/720/1176/nightlife/1/ 720w
"
data-sizes="auto"
```

If you really want to use x descriptors you can use picturefill.

**Comment by raphaelokon** [comment]
I am getting the same error on IE11 (in a testing VM) where the picture tag is generated but the `lazyload` class is stuck at `lazyloading` … and not `background` is written to the element's style.

**Comment by aFarkas** [comment]
@raphaelokon 
The problem above was fixed with 2.0.0. Can you provide a testcase for me.

**Comment by aFarkas** [comment]
@raphaelokon 
I would like to release a new version soon. It would help, if you could give me a testcase for your issue.

**Comment by raphaelokon** [comment]
@aFarkas 
It is a bit complex … the main difference between the test cases above is that I am setting the `data-beset` dynamically via JS on page-load (I have a pool of images to choose one from) so that the page can be cached properly – thus setting the random image on the client-side. I will code up a small example. I am also using ES6 -> ES5 …

**Comment by aFarkas** [comment]
@raphaelokon 

thx.

**Comment by raphaelokon** [comment]
@aFarkas I have done a small research and set up a test case with dynamically applying the bg-set …  it worked fine in IE 11 so I guess the bottleneck seems to be somewhere else. I could grant you a temp access to the staging page to see the bug under live circumstances.

**Comment by aFarkas** [comment]
@raphaelokon 
This would be great.  You can mail to my normal mail listed here: https://github.com/aFarkas

**Comment by aFarkas** [comment]
@raphaelokon 
did you mail me the url (with credentials if needed). because I did not get those.

**Comment by raphaelokon** [comment]
@aFarkas Sorry – was busy all day … I will create you a temp access account and mail you over.

**Comment by raphaelokon** [comment]
@aFarkas Okay! Fixed it. Was not a bug with Lazysizes at all! `loadJS` wasn't loading the `respimg` fallback due to proxy. All good!

**Comment by aFarkas** [comment]
Thanks
